### ISSUE TITLE
Fonts and images - source and license

### ISSUE THREAD

**Issue by mudrd8mz** [vidyamantra/moodle-theme_eduhub#4]
May I ask for a file https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml or just a README where it would be listed where the fonts come from and what is their license.

Same would be good to have explicitly mentioned for images - e.g. to make sure that you are the author and what license they can be redistributed under.

**Comment by susmita123** [comment]
Changes can be found at https://github.com/vidyamantra/moodle-theme_eduhub/commit/e612144885a743d4fc509186f604dbbf4ac6f080

**Comment by jgupta** [comment]
All images used are in public domain.
