### ISSUE TITLE
Breadcrumbs hide behind navbar with Larger Logo

### ISSUE THREAD

**Issue by mruasar** [vidyamantra/moodle-theme_eduhub#7]
The default logo works fine, but when logo with bigger height is used, it though expands the navbar perfectly, but then breadcrumbs gets hidden behind navbar.

**Comment by susmita123** [comment]
Thank You for your feedback. 
About this issue,
Please go to theme settings page ( Dashboard / Site administration / Appearance / Themes / Eduhub / General Settings  )  "Custom Css"

Add below css here. and save.
body{
  padding-top:100px;
}

Note : If your logo height is 100px, padding-top should be 100px.

**Comment by mruasar** [comment]
Cheers, Works well, please add this to Theme documentation (or just below logo upload) replacing the current CSS code.
