### ISSUE TITLE
Category List on FrontPage doesnt shows up

### ISSUE THREAD

**Issue by mruasar** [vidyamantra/moodle-theme_eduhub#9]
When enabled in "front page settings", it does however shows up Category list heading, but nothing appears from categories. 
![capture2](https://cloud.githubusercontent.com/assets/5184754/13036618/ca110f90-d38d-11e5-9f27-01c95b064aa7.PNG)

**Comment by susmita123** [comment]
![screen shot 2016-02-15 at 10 26 30 am](https://cloud.githubusercontent.com/assets/3794936/13040171/acfa4d72-d3ce-11e5-8876-5b5ea6524ca4.png)

Category List shows correctly. Please create your Category List and then check. If still there is same issue please share with us.

**Comment by mruasar** [comment]
Apologies, my bad for course tiles are sharing same div class, and I hide them for a test eventually hiding the Course Categories. shows up fine. Thanks!
